SERVICE_PREFIX=Event-Feedback: Analyzer
JAVA_XMX: 10g

spring:
  datasource:
    url: jdbc:h2:mem:analyzerdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


huggingface:
  api:
    url: https://router.huggingface.co/hf-inference/models/cardiffnlp/twitter-roberta-base-sentiment
    token:
